server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: country_flag_api
  logging:
    level:
      root: INFO
      com.example: DEBUG

api:
  country-flag:
    country-data-provider-url: "https://api.api-ninjas.com/v1"
    country-data-provider-url-2: "https://countriesnow.space"
    #This is not best practice. API Keys should not be in the property file. It should be set in secrets
    api-ninja-key: ${API_NINJA_KEY:gbbRJspHBSE7eVWOtWzuaQ==pgFOb5TC7i0pkHlW}
cors:
  #For production, specific origins should be specified
  originPatterns: "*"